backend:
  name: git-gateway
  # name: github
  repo: saulofilho/pagina-de-materiais
  branch: master
media_folder: static/assets
public_folder: /assets
collections:
  - name: post
    label: Post
    folder: data
    slug: '{{slug}}'
    create: true
    fields:
      - { name: date, label: Date, widget: datetime, required: false }
      - { name: title, label: Title, widget: string, required: false }
      - { name: body, label: Title, widget: markdown, required: false }
      - { name: link, label: Link, widget: string, required: false }
      - label: Image
        name: image
        widget: image
        required: false
        media_library:
          config:
            multiple: false
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["Destaque", "Materiais" ]
        default: ["Materiais"]
