backend:
  name: git-gateway
  # name: github
  repo: saulofilho/pagina-de-materiais
  branch: master
media_folder: static/assets
public_folder: /assets
collections:
  - name: post
    label: Post
    folder: data/posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - {
        label: Template,
        name: template,
        widget: hidden,
        default: BlogPost,
      }
      - { name: date, label: Date, widget: datetime, required: false }
      - { name: title, label: Title, widget: markdown, required: false }
      - { name: link, label: Link, widget: string, required: false }
      - label: Image
        name: image
        widget: image
        required: false
        media_library:
          config:
            multiple: false
