backend:
  name: git-gateway
  branch: master

display_url: https://santacontabilidade-pagina-de-materiais.netlify.app/

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Post
    folder: data
    slug: '{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Titulo, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { name: link, label: Link, widget: string }
      - label: Image
        name: image
        widget: image
        required: false
        media_library:
          config:
            multiple: false
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["Destaque", "Materiais" ]
        default: ["Materiais"]
